apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        application.kubernetes.io/logsrotate: '[{"name":"{{ .Values.name }}-logs", "rotate":""}]'
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-container
        image: {{ .Values.image.registry }}/{{ .Values.image.tag.app_service }}
        env:
        - name: JAVA_OPTS
          value: -Dspring.config.location=file:/app/application.yml -XX:+UseContainerSupport -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=80.0
        # rsources资源配额请根据自身应用情况申请
        resources: 
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0.2
            memory: 500Mi
        volumeMounts:
        - name: {{ .Values.name }}-config
          mountPath: /app/application.yml
          subPath: application.yml
        - mountPath: /app/logs
          name: {{ .Values.name }}-logs
      volumes:
      - name: {{ .Values.name }}-config
        configMap:
          name: {{ .Values.name }}-configmap
      - hostPath:
          path: /opt/ado/log/{{ .Values.name }}
          type: ""
        name: {{ .Values.name }}-logs
      imagePullSecrets:
      - name: kube-system-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.name }}-port
    port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: {{ .Values.name }}
