spring:
  application:
    name: demo
server:
  port: 8889
  max-http-header-size: 1048576 #jwt需要较多内容，需要设置大一些

ado:
  keystone:
    socketTimeout: 30000  #请求网络请求超时时间30秒
    connectTimeout: 30000  #请求网络连接超时时间30秒
    connectRequestTimeout: 30000  #请求获取请求连接超时时间30秒
    connectMaxTotal: 100    # 最大连接数
    connectPerRouteMax: 50   # 同源网站最大连接数
    supportedCipherSuites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    supportProtocols: TLSv1.2
    trustCertificateFile:   # 配置为空时，会忽略证书，需配置CA jks，存在隐患
    trustCertificatePassword:

# logging.level.root: debug

spring.servlet.multipart.enabled: false
# 整个premise集群的入口地址，使用时需替换成相关环境地址，按需修改namespace
ucmarket.baseurl: https://ado-gateway.kube-system.svc.cluster.local:443

# jwt检查公钥，取自ado-baseservice-cfg-configmap的gkit.iam.jwt.rsa.public
ucmarket.security.jwt.rsa.secret.public:
#检查token白名单配置，没有时配置为空，或者不配置
ucmarket.security.interceptor.url.whitelist: GET|/demo/test,GET|/error
# 获取用户信息接口
ucmarket.security.auth.url: ${ucmarket.baseurl}/auth/who
#权限检查服务地址
ucmarket.security.iam.url: ${ucmarket.baseurl}/iam
# 权限导入 开关
ucmarket.security.ado.app.tag.push.rest: true
ucmarket.security.ado.app.tag.push.mq: false
# 权限导入vAPP名称,为空时不开启导入功能 ，需要修改
ucmarket.security.ado.app.tag.app.code: democode
# 标签定义扫描包,建议尽量精准，提高高效率，减少错误 ，需要修改
ucmarket.security.ado.app.tag.item.scan.package: demo.tag
# 权限自动导入地址
ucmarket.security.ado.tag.app.import.url: ${ucmarket.baseurl}/iam/authorize/permissions/tags/{0}/import





# 机器账号配置
iam:
  ucmarket:
    url: ${ucmarket.baseurl}/iam/keystone/auth/getToken
    # 机机账号名
    username:
    # 机机密码
    password:
    domain: svc.app